CREATE TABLE ONU_INDIVIDUAL (
    DATAID VARCHAR(20) NOT NULL,
    VERSIONNUM INT,
    FIRST_NAME VARCHAR(200),
    SECOND_NAME VARCHAR(200),
    THIRD_NAME VARCHAR(200),
    UN_LIST_TYPE VARCHAR(200),
    REFERENCE_NUMBER VARCHAR(200),
    LISTED_ON DATE,
    NAME_ORIGINAL_SCRIPT VARCHAR(200),
    COMMENTS1 VARCHAR(500),
    DATE_GENERATED DATE,
    TYPE VARCHAR(100),
    PRIMARY KEY (DATAID)
);

CREATE TABLE ONU_INDIVIDUAL_ADDRESS (
    DATAID VARCHAR(20) NOT NULL,
    CITY VARCHAR(500) NOT NULL,
    COUNTRY VARCHAR(500) NOT NULL,
    STATE_PROVINCE VARCHAR(500) NOT NULL,
    NOTE VARCHAR(500) NOT NULL,
    STREET VARCHAR(500) NOT NULL,
    PRIMARY KEY (DATAID, COUNTRY, CITY, STATE_PROVINCE, STREET, NOTE),
    FOREIGN KEY (DATAID) REFERENCES ONU_INDIVIDUAL(DATAID)
);

CREATE TABLE ONU_INDIVIDUAL_ALIAS (
    DATAID VARCHAR(20) NOT NULL,
    QUALITY VARCHAR(200),
    ALIAS_NAME VARCHAR(500) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    CITY_OF_BIRTH VARCHAR(200) NOT NULL,
    NOTE VARCHAR(500) NOT NULL,
    COUNTRY_OF_BIRTH VARCHAR(200) NOT NULL,
    PRIMARY KEY (DATAID, ALIAS_NAME, DATE_OF_BIRTH, CITY_OF_BIRTH, NOTE, COUNTRY_OF_BIRTH),
    FOREIGN KEY (DATAID) REFERENCES ONU_INDIVIDUAL(DATAID)
);

CREATE TABLE ONU_INDIVIDUAL_DATE_OF_BIRTH (
    DATAID VARCHAR(20) NOT NULL,
    TYPE_OF_DATE VARCHAR(20),
    YEAR VARCHAR(20) NOT NULL,
    I_DATE DATE NOT NULL,
    FROM_YEAR VARCHAR(20) NOT NULL,
    TO_YEAR VARCHAR(20) NOT NULL,
    NOTE VARCHAR(200),
    PRIMARY KEY (DATAID, YEAR, I_DATE, FROM_YEAR, TO_YEAR),
    FOREIGN KEY (DATAID) REFERENCES ONU_INDIVIDUAL(DATAID)
);

CREATE TABLE ONU_INDIVIDUAL_DOCUMENT (
    DATAID VARCHAR(20) NOT NULL,
    TYPE_OF_DOCUMENT VARCHAR(500) NOT NULL,
    NUMBER_DOC VARCHAR(200) NOT NULL,
    ISSUING_COUNTRY VARCHAR(200),
    NOTE VARCHAR(500) NOT NULL,
    TYPE_OF_DOCUMENT2 VARCHAR(500) NOT NULL,
    PRIMARY KEY (DATAID, NUMBER_DOC, TYPE_OF_DOCUMENT, TYPE_OF_DOCUMENT2, NOTE),
    FOREIGN KEY (DATAID) REFERENCES ONU_INDIVIDUAL(DATAID)
);

CREATE TABLE ONU_INDIVIDUAL_PLACE_OF_BIRTH (
    DATAID VARCHAR(20) NOT NULL,
    CITY VARCHAR(500) NOT NULL,
    STATE_PROVINCE VARCHAR(500) NOT NULL,
    COUNTRY VARCHAR(500) NOT NULL,
    PRIMARY KEY (DATAID, CITY, STATE_PROVINCE, COUNTRY),
    FOREIGN KEY (DATAID) REFERENCES ONU_INDIVIDUAL(DATAID)
);

CREATE TABLE ONU_LAST_DAY_UPDATED (
    DATAID VARCHAR(20) NOT NULL,
    VALUE VARCHAR(20) NOT NULL,
    PRIMARY KEY (DATAID, VALUE),
    FOREIGN KEY (DATAID) REFERENCES ONU_INDIVIDUAL(DATAID)
);

CREATE TABLE ONU_NATIONALITY (
    DATAID VARCHAR(20) NOT NULL,
    VALUE VARCHAR(500) NOT NULL,
    PRIMARY KEY (DATAID, VALUE),
    FOREIGN KEY (DATAID) REFERENCES ONU_INDIVIDUAL(DATAID)
);

CREATE TABLE ONU_DESIGNATION (
    DATAID VARCHAR(20) NOT NULL,
    VALUE VARCHAR(500) NOT NULL,
    PRIMARY KEY (DATAID, VALUE),
    FOREIGN KEY (DATAID) REFERENCES ONU_INDIVIDUAL(DATAID)
);
